function rstudio(){var T='',Bb='" for "gwt:onLoadErrorFn"',zb='" for "gwt:onPropertyErrorFn"',mb='"><\/script>',bb='#',mc='.cache.html',db='/',pb='//',Zb='03619720D1AE1D6231F81E78EF42FB41',kc='0623D40E0A44D62681BC9EFB90291D94',lc=':',$b=':1',_b=':10',ac=':11',bc=':2',cc=':3',dc=':4',ec=':5',fc=':6',gc=':7',hc=':8',ic=':9',tb='::',oc='<script defer="defer">rstudio.onInjectionDone(\'rstudio\')<\/script>',lb='<script id="',wb='=',cb='?',yb='Bad handler "',nc='DOMContentLoaded',nb='SCRIPT',kb='__gwt_marker_rstudio',ob='base',gb='baseUrl',X='begin',W='bootstrap',fb='clear.cache.gif',Gb='compiler.stackMode',vb='content',Yb='emulated',ab='end',Jb='false',Sb='gecko',Tb='gecko1_8',Y='gwt.codesvr=',Z='gwt.hosted=',$='gwt.hybrid',Ab='gwt:onLoadErrorFn',xb='gwt:onPropertyErrorFn',ub='gwt:property',Wb='hosted.html?rstudio',Pb='ie10',Rb='ie8',Qb='ie9',Cb='iframe',eb='img',Db="javascript:''",Vb='loadExternalRefs',qb='meta',Fb='moduleRequested',_='moduleStartup',Ob='msie',rb='name',jc='native',Eb='position:absolute;width:0;height:0;border:none',U='rstudio',Hb='rstudio.cocoa',Kb='rstudio.desktop',ib='rstudio.nocache.js',sb='rstudio::',Nb='safari',hb='script',Xb='selectingPermutation',V='startup',Ib='true',jb='undefined',Ub='unknown',Lb='user.agent',Mb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=T,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:X});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Y)!=-1||(c.indexOf(Z)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf($)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(U);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return L(a)}}rstudio=null;c.gwtOnLoad(C,U,t,B);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:ab})}}
function H(){function e(a){var b=a.lastIndexOf(bb);if(b==-1){b=a.length}var c=a.indexOf(cb);if(c==-1){c=a.length}var d=a.lastIndexOf(db,Math.min(c,b));return d>=0?a.substring(0,d+1):T}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(eb);b.src=a+fb;a=e(b.src)}return a}
function g(){var a=J(gb);if(a!=null){return a}return T}
function h(){var a=n.getElementsByTagName(hb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ib)!=-1){return e(a[b].src)}}return T}
function i(){var a;if(typeof isBodyLoaded==jb||!isBodyLoaded()){var b=kb;var c;n.write(lb+b+mb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=nb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return T}
function j(){var a=n.getElementsByTagName(ob);if(a.length>0){return a[a.length-1].href}return T}
function k(){var a=n.location;return a.href==a.protocol+pb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==T){l=h()}if(l==T){l=i()}if(l==T){l=j()}if(l==T&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(qb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(rb),g;if(f){f=f.replace(sb,T);if(f.indexOf(tb)>=0){continue}if(f==ub){g=e.getAttribute(vb);if(g){var h,i=g.indexOf(wb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=T}u[f]=h}}else if(f==xb){g=e.getAttribute(vb);if(g){try{D=eval(g)}catch(a){alert(yb+g+zb)}}}else if(f==Ab){g=e.getAttribute(vb);if(g){try{C=eval(g)}catch(a){alert(yb+g+Bb)}}}}}}
function J(a){var b=u[a];return b==null?null:b}
function K(a,b){var c=A;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function L(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var M;function N(){if(!M){M=true;var a=n.createElement(Cb);a.src=Db;a.id=U;a.style.cssText=Eb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:Fb});a.contentWindow.location.replace(t+P)}}
w[Gb]=function(){return J(Gb)};v[Gb]={emulated:0,'native':1,strip:2};w[Hb]=function(){return window.desktop&&window.desktop.isCocoa()?Ib:Jb};v[Hb]={'false':0,'true':1};w[Kb]=function(){return window.desktop?Ib:Jb};v[Kb]={'false':0,'true':1};w[Lb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Mb)!=-1}())return Nb;if(function(){return b.indexOf(Ob)!=-1&&n.documentMode>=10}())return Pb;if(function(){return b.indexOf(Ob)!=-1&&n.documentMode>=9}())return Qb;if(function(){return b.indexOf(Ob)!=-1&&n.documentMode>=8}())return Rb;if(function(){return b.indexOf(Sb)!=-1}())return Tb;return Ub};v[Lb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};rstudio.onScriptLoad=function(){if(M){r=true;G()}};rstudio.onInjectionDone=function(){q=true;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:Vb,millis:(new Date).getTime(),type:ab});G()};I();H();var O;var P;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(U))){m.location.reload();return}P=Wb;O=T}o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:Xb});if(!F()){try{K([Yb,Jb,Jb,Tb],Zb);K([Yb,Jb,Jb,Pb],Zb+$b);K([Yb,Ib,Ib,Pb],Zb+_b);K([Yb,Ib,Ib,Nb],Zb+ac);K([Yb,Jb,Jb,Nb],Zb+bc);K([Yb,Jb,Ib,Tb],Zb+cc);K([Yb,Jb,Ib,Pb],Zb+dc);K([Yb,Jb,Ib,Nb],Zb+ec);K([Yb,Ib,Jb,Tb],Zb+fc);K([Yb,Ib,Jb,Pb],Zb+gc);K([Yb,Ib,Jb,Nb],Zb+hc);K([Yb,Ib,Ib,Tb],Zb+ic);K([jc,Jb,Jb,Tb],kc);K([jc,Jb,Jb,Pb],kc+$b);K([jc,Ib,Ib,Pb],kc+_b);K([jc,Ib,Ib,Nb],kc+ac);K([jc,Jb,Jb,Nb],kc+bc);K([jc,Jb,Ib,Tb],kc+cc);K([jc,Jb,Ib,Pb],kc+dc);K([jc,Jb,Ib,Nb],kc+ec);K([jc,Ib,Jb,Tb],kc+fc);K([jc,Ib,Jb,Pb],kc+gc);K([jc,Ib,Jb,Nb],kc+hc);K([jc,Ib,Ib,Tb],kc+ic);O=A[L(Gb)][L(Hb)][L(Kb)][L(Lb)];var Q=O.indexOf(lc);if(Q!=-1){B=Number(O.substring(Q+1));O=O.substring(0,Q)}P=O+mc}catch(a){return}}var R;function S(){if(!s){s=true;G();if(n.removeEventListener){n.removeEventListener(nc,S,false)}if(R){clearInterval(R)}}}
if(n.addEventListener){n.addEventListener(nc,function(){N();S()},false)}var R=setInterval(function(){if(/loaded|complete/.test(n.readyState)){N();S()}},50);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:ab});o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:Vb,millis:(new Date).getTime(),type:X});n.write(oc)}
rstudio();